/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.util.HashMap;
import javax.swing.JOptionPane;
import modelBeans.BeansClientes;
import modeloConection.ConexaoBD;
import static modeloConection.ConexaoBD.getConnection;
import modeloDao.DaoClientes;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Nilmar
 */
public class FichaCadastroClientes extends javax.swing.JFrame {

    BeansClientes mod = new BeansClientes();
    DaoClientes dao = new DaoClientes();
    ConexaoBD conex = new ConexaoBD();
    int flag=0;
    
    public FichaCadastroClientes() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_justica.png")).getImage());
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastrodeClientes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelRG = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelEstadoCivil = new javax.swing.JLabel();
        jTextFieldEstadoCivil = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jFormattedTextFieldRG = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jLabelProfissao = new javax.swing.JLabel();
        jTextFieldProfissao = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelTelefone = new javax.swing.JLabel();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jLabelNumeroDaPasta = new javax.swing.JLabel();
        jTextFieldIdCliente = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jFormattedTextFieldPesquisa = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabelRespNome = new javax.swing.JLabel();
        jTextFieldRespNome = new javax.swing.JTextField();
        jLabelRespParentesco = new javax.swing.JLabel();
        jTextFieldRespParentesco = new javax.swing.JTextField();
        jLabelRespEstadoCivil = new javax.swing.JLabel();
        jTextFieldRespEstadoCivil = new javax.swing.JTextField();
        jLabelRespProfissao = new javax.swing.JLabel();
        jTextFieldRespProfissao = new javax.swing.JTextField();
        jLabelRespRenda = new javax.swing.JLabel();
        jFormattedTextFieldRespRenda = new javax.swing.JFormattedTextField();
        jLabelRespRG = new javax.swing.JLabel();
        jFormattedTextFieldRespRG = new javax.swing.JFormattedTextField();
        jLabelRespCPF = new javax.swing.JLabel();
        jFormattedTextFieldRespCPF = new javax.swing.JFormattedTextField();
        jLabelRespEndereco = new javax.swing.JLabel();
        jTextFieldRespEndereco = new javax.swing.JTextField();
        jLabelRespBairro = new javax.swing.JLabel();
        jTextFieldRespBairro = new javax.swing.JTextField();
        jLabelRespNumeroCasa = new javax.swing.JLabel();
        jFormattedTextFieldRespNumeroCasa = new javax.swing.JFormattedTextField();
        jLabelRespCidade = new javax.swing.JLabel();
        jTextFieldRespCidade = new javax.swing.JTextField();
        jLabelRespEstado = new javax.swing.JLabel();
        jTextFieldRespEstado = new javax.swing.JTextField();
        jLabelRespTelefone = new javax.swing.JLabel();
        jFormattedTextFieldRespTelefone = new javax.swing.JFormattedTextField();
        jLabelRespCelular = new javax.swing.JLabel();
        jFormattedTextFieldRespCelular = new javax.swing.JFormattedTextField();
        jLabelNarracaofatos = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaNarracao = new javax.swing.JTextArea();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jLabelResponsavelLegal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabelCadastrodeClientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCadastrodeClientes.setText("CADASTRO DE CLIENTES");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNome.setText("Nome");

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelEmail.setText("E-mail");

        jLabelRG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRG.setText("RG");

        jTextFieldNome.setEnabled(false);

        jLabelEstadoCivil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelEstadoCivil.setText("Estado Civil");

        jTextFieldEstadoCivil.setEnabled(false);

        jLabelCPF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCPF.setText("CPF");

        try {
            jFormattedTextFieldRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldRG.setEnabled(false);

        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF.setEnabled(false);

        jLabelProfissao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelProfissao.setText("Profissão");

        jTextFieldProfissao.setEnabled(false);

        jTextFieldEmail.setEnabled(false);

        jLabelTelefone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTelefone.setText("Telefone");

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone.setEnabled(false);

        jLabelNumeroDaPasta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNumeroDaPasta.setText("Nº da Pasta");

        jTextFieldIdCliente.setEnabled(false);

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldPesquisa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jTextFieldEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEmail))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNumeroDaPasta, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFormattedTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelRG, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNumeroDaPasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonBuscar)
                            .addComponent(jFormattedTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelRespNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRespNome.setText("Nome");

        jTextFieldRespNome.setEnabled(false);

        jLabelRespParentesco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRespParentesco.setText("Parentesco");

        jTextFieldRespParentesco.setEnabled(false);

        jLabelRespEstadoCivil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRespEstadoCivil.setText("Estado Civil");

        jTextFieldRespEstadoCivil.setEnabled(false);

        jLabelRespProfissao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRespProfissao.setText("Profissão");

        jTextFieldRespProfissao.setEnabled(false);

        jLabelRespRenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRespRenda.setText("Renda Familiar");

        jFormattedTextFieldRespRenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextFieldRespRenda.setEnabled(false);
        jFormattedTextFieldRespRenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldRespRendaActionPerformed(evt);
            }
        });

        jLabelRespRG.setText("RG");

        try {
            jFormattedTextFieldRespRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldRespRG.setEnabled(false);

        jLabelRespCPF.setText("CPF");

        try {
            jFormattedTextFieldRespCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldRespCPF.setEnabled(false);

        jLabelRespEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRespEndereco.setText("Endereço");

        jTextFieldRespEndereco.setEnabled(false);

        jLabelRespBairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRespBairro.setText("Bairro");

        jTextFieldRespBairro.setEnabled(false);

        jLabelRespNumeroCasa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRespNumeroCasa.setText("Nº da Casa");

        jFormattedTextFieldRespNumeroCasa.setEnabled(false);

        jLabelRespCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRespCidade.setText("Cidade");

        jTextFieldRespCidade.setEnabled(false);

        jLabelRespEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRespEstado.setText("Estado");

        jTextFieldRespEstado.setEnabled(false);

        jLabelRespTelefone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRespTelefone.setText("Telefone");

        try {
            jFormattedTextFieldRespTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldRespTelefone.setEnabled(false);

        jLabelRespCelular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRespCelular.setText("Celular");

        try {
            jFormattedTextFieldRespCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldRespCelular.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelRespEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRespBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRespRG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRespProfissao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jLabelRespNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jFormattedTextFieldRespRG, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelRespCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFormattedTextFieldRespCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldRespProfissao)
                    .addComponent(jTextFieldRespNome)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldRespBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelRespNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldRespNumeroCasa))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldRespEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabelRespTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRespParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRespRenda, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRespEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRespCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRespCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jFormattedTextFieldRespRenda, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jTextFieldRespParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelRespEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldRespEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextFieldRespEndereco))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldRespTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabelRespCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldRespCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRespNome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRespNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRespParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRespParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRespEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRespEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRespProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRespProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRespRenda, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldRespRenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRespRG, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldRespRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRespCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldRespCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRespEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRespEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRespBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRespBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRespNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldRespNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRespCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRespCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRespTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRespCelular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelRespEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldRespEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextFieldRespTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextFieldRespCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jLabelNarracaofatos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNarracaofatos.setText("Narração dos Fatos:");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextAreaNarracao.setColumns(20);
        jTextAreaNarracao.setRows(5);
        jTextAreaNarracao.setEnabled(false);
        jScrollPane2.setViewportView(jTextAreaNarracao);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonNovo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.setEnabled(false);
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        jLabelResponsavelLegal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelResponsavelLegal.setText("Responsável Legal:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabelCadastrodeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNarracaofatos, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelResponsavelLegal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelCadastrodeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelResponsavelLegal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNarracaofatos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonImprimir))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1005, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    // AÇÃO DO BOTÃO NOVO
    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag =1; 
        jTextFieldNome.setEnabled(true);
        jTextFieldEstadoCivil.setEnabled(true);
        jTextFieldProfissao.setEnabled(true);
        jFormattedTextFieldRG.setEnabled(true);
        jFormattedTextFieldCPF.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jTextFieldRespNome.setEnabled(true);
        jTextFieldRespParentesco.setEnabled(true);
        jTextFieldRespEstadoCivil.setEnabled(true);
        jTextFieldRespProfissao.setEnabled(true);
        jFormattedTextFieldRespRenda.setEnabled(true);
        jFormattedTextFieldRespRG.setEnabled(true);
        jFormattedTextFieldRespCPF.setEnabled(true);
        jTextFieldRespEndereco.setEnabled(true);
        jTextFieldRespBairro.setEnabled(true);
        jFormattedTextFieldRespNumeroCasa.setEnabled(true);
        jTextFieldRespEstado.setEnabled(true);
        jTextFieldRespCidade.setEnabled(true);
        jFormattedTextFieldRespTelefone.setEnabled(true);
        jFormattedTextFieldRespCelular.setEnabled(true);
        jTextAreaNarracao.setEnabled(true);
        jFormattedTextFieldPesquisa.setEnabled(false);
        
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonBuscar.setEnabled(false);
        
        jTextFieldNome.setText("");
        jTextFieldEstadoCivil.setText("");
        jTextFieldProfissao.setText("");
        jFormattedTextFieldRG.setText("");
        jFormattedTextFieldCPF.setText("");
        jFormattedTextFieldTelefone.setText("");
        jTextFieldEmail.setText("");
        jTextFieldRespNome.setText("");
        jTextFieldRespParentesco.setText("");
        jTextFieldRespEstadoCivil.setText("");
        jTextFieldRespProfissao.setText("");
        jFormattedTextFieldRespRG.setText("");
        jFormattedTextFieldRespCPF.setText("");
        jTextFieldRespEndereco.setText("");
        jTextFieldRespBairro.setText("");
        jFormattedTextFieldRespNumeroCasa.setText("");
        jFormattedTextFieldRespRenda.setText("");
        jTextFieldRespCidade.setText("");
        jTextFieldRespCidade.setText("");
        jFormattedTextFieldRespTelefone.setText("");
        jFormattedTextFieldRespCelular.setText("");
        jTextAreaNarracao.setLineWrap(true); //jTextAreaNarracao.setText("");
    }//GEN-LAST:event_jButtonNovoActionPerformed

    
    // AÇÃO DO BOTÃO EDITAR
    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;
        jTextFieldNome.setEnabled(true);
        jTextFieldEstadoCivil.setEnabled(true);
        jTextFieldProfissao.setEnabled(true);
        jFormattedTextFieldRG.setEnabled(true);
        jFormattedTextFieldCPF.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jTextFieldRespNome.setEnabled(true);
        jTextFieldRespParentesco.setEnabled(true);
        jTextFieldRespEstadoCivil.setEnabled(true);
        jTextFieldRespProfissao.setEnabled(true);
        jFormattedTextFieldRespRG.setEnabled(true);
        jFormattedTextFieldRespCPF.setEnabled(true);
        jTextFieldRespEndereco.setEnabled(true);
        jFormattedTextFieldRespRenda.setEnabled(true);
        jTextFieldRespBairro.setEnabled(true);
        jFormattedTextFieldRespNumeroCasa.setEnabled(true);
        jTextFieldRespCidade.setEnabled(true);
        jTextFieldRespEstado.setEnabled(true);
        jFormattedTextFieldRespTelefone.setEnabled(true);
        jFormattedTextFieldRespCelular.setEnabled(true);
        jTextAreaNarracao.setEnabled(true);
        jTextAreaNarracao.setLineWrap(true);
        jFormattedTextFieldPesquisa.setEnabled(false);
        
        jButtonSalvar.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jButtonNovo.setEnabled(false); 
        jButtonEditar.setEnabled(false);
        jButtonBuscar.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    
    // AÇÃO DO BOTÃO CANCELAR
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldNome.setEnabled(!true);
        jTextFieldEstadoCivil.setEnabled(!true);
        jTextFieldProfissao.setEnabled(!true);
        jFormattedTextFieldRG.setEnabled(!true);
        jFormattedTextFieldCPF.setEnabled(!true);
        jFormattedTextFieldTelefone.setEnabled(!true);
        jTextFieldEmail.setEnabled(!true);
        jTextFieldRespNome.setEnabled(!true);
        jTextFieldRespParentesco.setEnabled(!true);
        jTextFieldRespEstadoCivil.setEnabled(!true);
        jTextFieldRespProfissao.setEnabled(!true);
        jFormattedTextFieldRespRG.setEnabled(!true);
        jFormattedTextFieldRespCPF.setEnabled(!true);
        jTextFieldRespEndereco.setEnabled(!true);
        jTextFieldRespBairro.setEnabled(!true);
        jFormattedTextFieldRespNumeroCasa.setEnabled(!true);
        jFormattedTextFieldRespRenda.setEnabled(!true);
        jTextFieldRespCidade.setEnabled(!true);
        jTextFieldRespEstado.setEnabled(!true);
        jFormattedTextFieldRespTelefone.setEnabled(!true);
        jFormattedTextFieldRespCelular.setEnabled(!true);
        jTextAreaNarracao.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jFormattedTextFieldPesquisa.setEnabled(true);
        jButtonBuscar.setEnabled(true);
        
        jTextFieldNome.setText("");
        jTextFieldEstadoCivil.setText("");
        jTextFieldProfissao.setText("");
        jFormattedTextFieldRG.setText("");
        jFormattedTextFieldCPF.setText("");
        jFormattedTextFieldTelefone.setText("");
        jTextFieldEmail.setText("");
        jTextFieldRespNome.setText("");
        jTextFieldRespParentesco.setText("");
        jTextFieldRespEstadoCivil.setText("");
        jFormattedTextFieldRespRenda.setText("");
        jTextFieldProfissao.setText("");
        jFormattedTextFieldRespRG.setText("");
        jFormattedTextFieldRespCPF.setText("");
        jTextFieldRespEndereco.setText("");
        jTextFieldRespBairro.setText("");
        jFormattedTextFieldRespNumeroCasa.setText("");
        jTextFieldRespCidade.setText("");
        jTextFieldRespCidade.setText("");
        jFormattedTextFieldRespTelefone.setText("");
        jFormattedTextFieldRespCelular.setText("");
        jTextAreaNarracao.setText("");  
        jFormattedTextFieldPesquisa.setText("");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    // AÇÃO DO BOTÃO SALVAR
    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if(jTextFieldNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo nome para continuar");
            jTextFieldNome.requestFocus();
        }else if(jTextFieldEstadoCivil.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo estado civil para continuar");
            jTextFieldEstadoCivil.requestFocus();            
        }else if(jTextFieldProfissao.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo profissão para continuar");
            jTextFieldProfissao.requestFocus();
        }else if(jFormattedTextFieldRG.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo RG para continuar");
            jFormattedTextFieldRG.requestFocus();
        }else if(jFormattedTextFieldCPF.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo CPF para continuar");
            jFormattedTextFieldCPF.requestFocus();    
        }else if(jFormattedTextFieldTelefone.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo telefone para continuar");
            jFormattedTextFieldTelefone.requestFocus();
        }else if(jTextFieldEmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo e-mail para continuar");
            jTextFieldEmail.requestFocus();
        }else if(jTextFieldRespNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo nome para continuar");
            jTextFieldRespNome.requestFocus();
        }else if(jTextFieldRespParentesco.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo parentesco para continuar");
            jTextFieldRespParentesco.requestFocus();
        }else if(jTextFieldRespEstadoCivil.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo estado civil para continuar");
            jTextFieldRespEstadoCivil.requestFocus(); 
        }else if(jTextFieldRespProfissao.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo profissão para continuar");
            jTextFieldRespProfissao.requestFocus();
        }else if(jFormattedTextFieldRespRenda.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo renda familiar para continuar");
            jFormattedTextFieldRespRenda.requestFocus();  
        }else if(jFormattedTextFieldRG.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo RG para continuar");
            jFormattedTextFieldRespRG.requestFocus();
        }else if(jFormattedTextFieldRespCPF.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo CPF para continuar");
            jFormattedTextFieldRespCPF.requestFocus();
        }else if(jTextFieldRespEndereco.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo endereço para continuar");
            jTextFieldRespEndereco.requestFocus();
        }else if(jTextFieldRespBairro.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo bairro para continuar");
            jTextFieldRespBairro.requestFocus();
        }else if(jFormattedTextFieldRespNumeroCasa.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo numero da casa para continuar");
            jFormattedTextFieldRespNumeroCasa.requestFocus();    
        }else if(jTextFieldRespCidade.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo cidade para continuar");
            jTextFieldRespCidade.requestFocus();
        }else if(jTextFieldRespEstado.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo estado para continuar");
            jTextFieldRespEstado.requestFocus();
        }else if(jFormattedTextFieldRespTelefone.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo telefone para continuar");
            jFormattedTextFieldRespTelefone.requestFocus();
        }else if(jFormattedTextFieldRespCelular.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo celular para continuar");
            jFormattedTextFieldRespCelular.requestFocus(); 
        }else if(jTextAreaNarracao.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo narração dos fatos para continuar");
            jTextAreaNarracao.requestFocus();    
        }else{
        if(flag == 1){
        mod.setNome_Cliente(jTextFieldNome.getText());
        mod.setEstadoCivil_Cliente(jTextFieldEstadoCivil.getText());
        mod.setProfissao_Cliente(jTextFieldProfissao.getText());
        mod.setRG_Cliente(jFormattedTextFieldRG.getText());
        mod.setCPF_Cliente(jFormattedTextFieldCPF.getText());
        mod.setTelefone_Cliente(jFormattedTextFieldTelefone.getText());
        mod.setEmail_Cliente(jTextFieldEmail.getText());
        mod.setNome_Responsavel(jTextFieldRespNome.getText());
        mod.setParentesco_Responsavel(jTextFieldRespParentesco.getText());
        mod.setEstadoCivil_Responsavel(jTextFieldRespEstadoCivil.getText());
        mod.setProfisao_Responsavel(jTextFieldRespProfissao.getText());
        mod.setRenda_Responsavel(jFormattedTextFieldRespRenda.getText());
        mod.setRG_Responsavel(jFormattedTextFieldRespRG.getText());
        mod.setCPF_Responsavel(jFormattedTextFieldRespCPF.getText());
        mod.setEndereco_Responsavel(jTextFieldRespEndereco.getText());
        mod.setBairro_Responsavel(jTextFieldRespBairro.getText());
        mod.setNumeroCasa_Responsavel(jFormattedTextFieldRespNumeroCasa.getText());
        mod.setCidade_Responsavel(jTextFieldRespCidade.getText());
        mod.setEstado_Responsavel(jTextFieldRespEstado.getText());
        mod.setTelefone_Responsavel(jFormattedTextFieldRespTelefone.getText());
        mod.setCelular_Responsavel(jFormattedTextFieldRespCelular.getText());
        mod.setNarracaoFatos(jTextAreaNarracao.getText());
        File diretorio = new File("C:\\SistemaNPJ\\"+jTextFieldNome.getText());
        if(!diretorio.exists())
            diretorio.mkdir();
        dao.salvar(mod);
        
        jTextFieldNome.setText("");
        jTextFieldEstadoCivil.setText("");
        jTextFieldProfissao.setText("");
        jFormattedTextFieldRG.setText("");
        jFormattedTextFieldCPF.setText("");
        jFormattedTextFieldTelefone.setText("");
        jTextFieldEmail.setText("");
        jTextFieldRespNome.setText("");
        jTextFieldRespParentesco.setText("");
        jTextFieldRespEstadoCivil.setText("");
        jTextFieldRespProfissao.setText("");
        jFormattedTextFieldRespRenda.setText("");
        jFormattedTextFieldRespRG.setText("");
        jFormattedTextFieldRespCPF.setText("");
        jTextFieldRespEndereco.setText("");
        jTextFieldRespBairro.setText("");
        jFormattedTextFieldRespNumeroCasa.setText("");
        jFormattedTextFieldRespRenda.setText("");
        jTextFieldRespCidade.setText("");
        jTextFieldRespEstado.setText("");
        jFormattedTextFieldRespTelefone.setText("");
        jFormattedTextFieldRespCelular.setText("");
        jTextAreaNarracao.setText("");
        
        jTextFieldNome.setEnabled(!true);
        jTextFieldEstadoCivil.setEnabled(!true);
        jTextFieldProfissao.setEnabled(!true);
        jFormattedTextFieldRG.setEnabled(!true);
        jFormattedTextFieldCPF.setEnabled(!true);
        jFormattedTextFieldTelefone.setEnabled(!true);
        jTextFieldEmail.setEnabled(!true);
        jTextFieldRespNome.setEnabled(!true);
        jTextFieldRespParentesco.setEnabled(!true);
        jTextFieldRespEstadoCivil.setEnabled(!true);
        jTextFieldRespProfissao.setEnabled(!true);
        jFormattedTextFieldRespRenda.setEnabled(!true);
        jFormattedTextFieldRespRG.setEnabled(!true);
        jFormattedTextFieldRespCPF.setEnabled(!true);
        jTextFieldRespEndereco.setEnabled(!true);
        jTextFieldRespBairro.setEnabled(!true);
        jFormattedTextFieldRespNumeroCasa.setEnabled(!true);
        jTextFieldRespEstado.setEnabled(!true);
        jTextFieldRespCidade.setEnabled(!true);
        jFormattedTextFieldRespTelefone.setEnabled(!true);
        jFormattedTextFieldRespCelular.setEnabled(!true);
        jTextAreaNarracao.setEnabled(!true);

        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jTextFieldIdCliente.setText("");
        jButtonCancelar.setEnabled(false);
        jFormattedTextFieldPesquisa.setEnabled(true);
        jButtonBuscar.setEnabled(true);
        }
        }if(flag == 2){
        mod.setId_Cliente(Integer.parseInt(jTextFieldIdCliente.getText()));
        mod.setNome_Cliente(jTextFieldNome.getText());
        mod.setEstadoCivil_Cliente(jTextFieldEstadoCivil.getText());
        mod.setProfissao_Cliente(jTextFieldProfissao.getText());
        mod.setRG_Cliente(jFormattedTextFieldRG.getText());
        mod.setCPF_Cliente(jFormattedTextFieldCPF.getText());
        mod.setTelefone_Cliente(jFormattedTextFieldTelefone.getText());
        mod.setEmail_Cliente(jTextFieldEmail.getText());
        mod.setNome_Responsavel(jTextFieldRespNome.getText());
        mod.setParentesco_Responsavel(jTextFieldRespParentesco.getText());
        mod.setEstadoCivil_Responsavel(jTextFieldRespEstadoCivil.getText());
        mod.setProfisao_Responsavel(jTextFieldRespProfissao.getText());
        mod.setRenda_Responsavel(jFormattedTextFieldRespRenda.getText());
        mod.setRG_Responsavel(jFormattedTextFieldRespRG.getText());
        mod.setCPF_Responsavel(jFormattedTextFieldRespCPF.getText());
        mod.setEndereco_Responsavel(jTextFieldRespEndereco.getText());
        mod.setBairro_Responsavel(jTextFieldRespBairro.getText());
        mod.setNumeroCasa_Responsavel(jFormattedTextFieldRespNumeroCasa.getText());
        mod.setCidade_Responsavel(jTextFieldRespCidade.getText());
        mod.setEstado_Responsavel(jTextFieldRespEstado.getText());
        mod.setTelefone_Responsavel(jFormattedTextFieldRespTelefone.getText());
        mod.setCelular_Responsavel(jFormattedTextFieldRespCelular.getText());
        mod.setNarracaoFatos(jTextAreaNarracao.getText());
        dao.alterar(mod);
        
        jTextFieldIdCliente.setText("");
        jTextFieldNome.setText("");
        jTextFieldEstadoCivil.setText("");
        jTextFieldProfissao.setText("");
        jFormattedTextFieldRG.setText("");
        jFormattedTextFieldCPF.setText("");
        jFormattedTextFieldTelefone.setText("");
        jTextFieldEmail.setText("");
        jTextFieldRespNome.setText("");
        jTextFieldRespParentesco.setText("");
        jTextFieldRespEstadoCivil.setText("");
        jTextFieldRespProfissao.setText("");
        jFormattedTextFieldRespRenda.setText("");
        jFormattedTextFieldRespRG.setText("");
        jFormattedTextFieldRespCPF.setText("");
        jTextFieldRespEndereco.setText("");
        jTextFieldRespBairro.setText("");
        jFormattedTextFieldRespNumeroCasa.setText("");
        jFormattedTextFieldRespRenda.setText("");
        jTextFieldRespCidade.setText("");
        jTextFieldRespEstado.setText("");
        jFormattedTextFieldRespTelefone.setText("");
        jFormattedTextFieldRespCelular.setText("");
        jTextAreaNarracao.setText("");
        jFormattedTextFieldPesquisa.setText("");
        
        jTextFieldNome.setEnabled(!true);
        jTextFieldEstadoCivil.setEnabled(!true);
        jTextFieldProfissao.setEnabled(!true);
        jFormattedTextFieldRG.setEnabled(!true);
        jFormattedTextFieldCPF.setEnabled(!true);
        jFormattedTextFieldTelefone.setEnabled(!true);
        jTextFieldEmail.setEnabled(!true);
        jTextFieldRespNome.setEnabled(!true);
        jTextFieldRespParentesco.setEnabled(!true);
        jTextFieldRespEstadoCivil.setEnabled(!true);
        jTextFieldRespProfissao.setEnabled(!true);
        jFormattedTextFieldRespRenda.setEnabled(!true);
        jFormattedTextFieldRespRG.setEnabled(!true);
        jFormattedTextFieldRespCPF.setEnabled(!true);
        jTextFieldRespEndereco.setEnabled(!true);
        jTextFieldRespBairro.setEnabled(!true);
        jFormattedTextFieldRespNumeroCasa.setEnabled(!true);
        jTextFieldRespEstado.setEnabled(!true);
        jTextFieldRespCidade.setEnabled(!true);
        jFormattedTextFieldRespTelefone.setEnabled(!true);
        jFormattedTextFieldRespCelular.setEnabled(!true);
        jTextAreaNarracao.setEnabled(!true);

        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonCancelar.setEnabled(false);
        jFormattedTextFieldPesquisa.setEnabled(true);
        jButtonBuscar.setEnabled(true);
        jButtonImprimir.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    // AÇÃO DO BOTÃO EXCLUIR
    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir? ");
        if(resposta == JOptionPane.YES_OPTION){
        mod.setCPF_Cliente(jFormattedTextFieldCPF.getText()); 
        File diretorio = new File("C:\\SistemaNPJ\\"+jTextFieldNome.getText());
            if(diretorio.exists()){
                removerArquivos(diretorio);
            }
        dao.excluir(mod); 
        jTextFieldNome.setText("");
        jTextFieldEstadoCivil.setText("");
        jTextFieldProfissao.setText("");
        jFormattedTextFieldRG.setText("");
        jFormattedTextFieldCPF.setText("");
        jFormattedTextFieldTelefone.setText("");
        jTextFieldEmail.setText("");
        jTextFieldRespNome.setText("");
        jTextFieldRespParentesco.setText("");
        jTextFieldRespEstadoCivil.setText("");
        jTextFieldProfissao.setText("");
        jFormattedTextFieldRespRG.setText("");
        jFormattedTextFieldRespCPF.setText("");
        jTextFieldRespEndereco.setText("");
        jTextFieldRespBairro.setText("");
        jFormattedTextFieldRespNumeroCasa.setText("");
        jTextFieldRespCidade.setText("");
        jTextFieldRespCidade.setText("");
        jFormattedTextFieldRespTelefone.setText("");
        jFormattedTextFieldRespCelular.setText("");
        jTextAreaNarracao.setText("");
        jFormattedTextFieldPesquisa.setText("");
        jTextFieldIdCliente.setText("");
        jFormattedTextFieldRespRenda.setText("");
        jTextFieldRespEstado.setText("");
        
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonNovo.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    // METÓDO PARA APAGAR A PASTA DO USUÁRIO
    public void removerArquivos(File f) {
     if (f.isDirectory()) {
        File[] files = f.listFiles();
        for (File file : files) {
            removerArquivos(file);
         }
     }
     f.delete();
  }
    
    // AÇÃO DO BOTÃO IMPRIMIR 
    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        imprimirFicha();
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    
    // AÇÃO DO BOTÃO BUSCAR
    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        mod.setPesquisa(jFormattedTextFieldPesquisa.getText());
        BeansClientes model = dao.busca_clientes(mod);
        jTextFieldIdCliente.setText(String.valueOf(model.getId_Cliente()));
        jTextFieldNome.setText(model.getNome_Cliente());
        jTextFieldEstadoCivil.setText(model.getEstadoCivil_Cliente());
        jTextFieldProfissao.setText(model.getProfissao_Cliente());
        jFormattedTextFieldRG.setText(model.getRG_Cliente());
        jFormattedTextFieldCPF.setText(model.getCPF_Cliente());
        jFormattedTextFieldTelefone.setText(model.getTelefone_Cliente());
        jTextFieldEmail.setText(model.getEmail_Cliente());
        jTextFieldRespNome.setText(model.getNome_Responsavel());
        jTextFieldRespParentesco.setText(model.getParentesco_Responsavel());
        jTextFieldRespEstadoCivil.setText(model.getEstadoCivil_Responsavel());
        jTextFieldRespProfissao.setText(model.getProfisao_Responsavel());
        jFormattedTextFieldRespRenda.setText(model.getRenda_Responsavel());
        jFormattedTextFieldRespRG.setText(model.getRG_Responsavel());
        jFormattedTextFieldRespCPF.setText(model.getCPF_Responsavel());
        jTextFieldRespEndereco.setText(model.getEndereco_Responsavel());
        jTextFieldRespBairro.setText(model.getBairro_Responsavel());
        jFormattedTextFieldRespNumeroCasa.setText(String.valueOf(model.getNumeroCasa_Responsavel()));
        jFormattedTextFieldRespRenda.setText(model.getRenda_Responsavel());
        jTextFieldRespCidade.setText(model.getCidade_Responsavel());
        jTextFieldRespEstado.setText(model.getEstado_Responsavel());
        jFormattedTextFieldRespTelefone.setText(model.getTelefone_Responsavel());
        jFormattedTextFieldRespCelular.setText(model.getCelular_Responsavel());
        jTextAreaNarracao.setText(model.getNarracaoFatos());
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonCancelar.setEnabled(!false);
        jButtonNovo.setEnabled(!true);
        jButtonImprimir.setEnabled(true);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jFormattedTextFieldRespRendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldRespRendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldRespRendaActionPerformed
    
    
    //  METODO PARA IMPRIMIR O RELATÓRIO
    private void imprimirFicha(){
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão do relatório? ", "Atenção",JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION){
            try {
            HashMap filtro = new HashMap();
            filtro.put("id_cliente", Integer.parseInt(jTextFieldIdCliente.getText())); //C:\\Users\\Nilma\\Desktop\\ProjetoNPJ\\FichaClientes\\FichaCliente.jasper
            JasperPrint print = JasperFillManager.fillReport("C:\\FichaClientes\\FichaCliente.jasper",filtro,getConnection());
            JasperViewer.viewReport(print, false);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao imprimir "+ex);
            }
        }
    }
    
      /**
     * @param args the command line arguments
     */
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FichaCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FichaCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FichaCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FichaCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FichaCadastroClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldPesquisa;
    private javax.swing.JFormattedTextField jFormattedTextFieldRG;
    private javax.swing.JFormattedTextField jFormattedTextFieldRespCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldRespCelular;
    private javax.swing.JFormattedTextField jFormattedTextFieldRespNumeroCasa;
    private javax.swing.JFormattedTextField jFormattedTextFieldRespRG;
    private javax.swing.JFormattedTextField jFormattedTextFieldRespRenda;
    private javax.swing.JFormattedTextField jFormattedTextFieldRespTelefone;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCadastrodeClientes;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEstadoCivil;
    private javax.swing.JLabel jLabelNarracaofatos;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumeroDaPasta;
    private javax.swing.JLabel jLabelProfissao;
    private javax.swing.JLabel jLabelRG;
    private javax.swing.JLabel jLabelRespBairro;
    private javax.swing.JLabel jLabelRespCPF;
    private javax.swing.JLabel jLabelRespCelular;
    private javax.swing.JLabel jLabelRespCidade;
    private javax.swing.JLabel jLabelRespEndereco;
    private javax.swing.JLabel jLabelRespEstado;
    private javax.swing.JLabel jLabelRespEstadoCivil;
    private javax.swing.JLabel jLabelRespNome;
    private javax.swing.JLabel jLabelRespNumeroCasa;
    private javax.swing.JLabel jLabelRespParentesco;
    private javax.swing.JLabel jLabelRespProfissao;
    private javax.swing.JLabel jLabelRespRG;
    private javax.swing.JLabel jLabelRespRenda;
    private javax.swing.JLabel jLabelRespTelefone;
    private javax.swing.JLabel jLabelResponsavelLegal;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaNarracao;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEstadoCivil;
    private javax.swing.JTextField jTextFieldIdCliente;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldProfissao;
    private javax.swing.JTextField jTextFieldRespBairro;
    private javax.swing.JTextField jTextFieldRespCidade;
    private javax.swing.JTextField jTextFieldRespEndereco;
    private javax.swing.JTextField jTextFieldRespEstado;
    private javax.swing.JTextField jTextFieldRespEstadoCivil;
    private javax.swing.JTextField jTextFieldRespNome;
    private javax.swing.JTextField jTextFieldRespParentesco;
    private javax.swing.JTextField jTextFieldRespProfissao;
    // End of variables declaration//GEN-END:variables

}
