/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import modelBeans.BeansRelatorioAcomp;
import modeloConection.ConexaoBD;
import modeloDao.DaoRelatorioAcomp;
import modelBeans.ModeloTabela;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import static modeloConection.ConexaoBD.getConnection;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Nilmar
 */
public class Relatorio extends javax.swing.JFrame {

    BeansRelatorioAcomp mod = new BeansRelatorioAcomp();
    DaoRelatorioAcomp dao = new DaoRelatorioAcomp();
    DaoRelatorioAcomp control = new DaoRelatorioAcomp();
    ConexaoBD conex = new ConexaoBD();
    
    public Relatorio() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_justica.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jFormattedTextNPasta = new javax.swing.JFormattedTextField();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRelatorio = new javax.swing.JTable();
        jButtonImprimir = new javax.swing.JButton();
        jLabelData = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabelDescricao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jLabelCodAcompanhamento = new javax.swing.JLabel();
        jTextFieldCodAcomp = new javax.swing.JTextField();
        jButtonImprimirTodos = new javax.swing.JButton();
        jLabelRelatorio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        try {
            jFormattedTextNPasta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextNPasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextNPastaActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Pesquisar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jTableRelatorio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRelatorioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRelatorio);

        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        jLabelData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelData.setText("Data:");

        jDateChooser1.setEnabled(false);

        jLabelDescricao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDescricao.setText("Última atualização:");

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jTextAreaDescricao.setEnabled(false);
        jScrollPane2.setViewportView(jTextAreaDescricao);

        jLabelCodAcompanhamento.setText("Cod. do Acompanhamento");

        jTextFieldCodAcomp.setEnabled(false);

        jButtonImprimirTodos.setText("Imprimir Todos");
        jButtonImprimirTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonImprimirTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jFormattedTextNPasta, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263)
                        .addComponent(jLabelCodAcompanhamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextNPasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jLabelCodAcompanhamento)
                    .addComponent(jTextFieldCodAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonImprimir)
                    .addComponent(jButtonImprimirTodos))
                .addContainerGap())
        );

        jLabelRelatorio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRelatorio.setText("Relatórios de Acompanhamento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(306, 306, 306))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(952, 529));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   // AÇÃO DO BOTÃO DE BUSCAR
    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        mod.setPesquisa(jFormattedTextNPasta.getText());
        BeansRelatorioAcomp model = dao.buscar_acomp(mod);
        jDateChooser1.setDate(model.getData());
        jTextFieldCodAcomp.setText(String.valueOf(model.getAcompanhamentoCod()));
        jTextAreaDescricao.setText(model.getNarracao());
        preencheTabela("select distinct cod_acompanhamento,acompanhamento_idcliente,acompanhamento_data,acompanhamento_descricao from acompanhamento where acompanhamento_idcliente like '%"+mod.getPesquisa()+"%'");
        jTableRelatorio.setVisible(true);
    }//GEN-LAST:event_jButtonBuscarActionPerformed
    
    // AÇÃO DO CLIQUE DO MOUSE
    private void jTableRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRelatorioMouseClicked
        String cod_cliente =""+jTableRelatorio.getValueAt(jTableRelatorio.getSelectedRow(), 0);
        conex.getConnection();
        conex.executasql("select *from acompanhamento where cod_acompanhamento='"+cod_cliente+"'");
        try {
            conex.rs.first();
            jTextAreaDescricao.setLineWrap(true);
            jFormattedTextNPasta.setText(conex.rs.getString("acompanhamento_idcliente"));
            jTextAreaDescricao.setText(conex.rs.getString("acompanhamento_descricao"));
            jDateChooser1.setDate(conex.rs.getDate("acompanhamento_data"));
            jTextFieldCodAcomp.setText(String.valueOf(conex.rs.getInt("cod_acompanhamento")));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados "+ex);
        }
        conex.desconectar();
    }//GEN-LAST:event_jTableRelatorioMouseClicked

    private void jFormattedTextNPastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextNPastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextNPastaActionPerformed

    
    // AÇÃO DO BOTÃO DE IMPRIMIR
    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        imprimirFicha();
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    // AÇÃO DO BOTÃO DE IMPRIMIR TODOS
    private void jButtonImprimirTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirTodosActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja realizar a impressão de todos os relatório? ", "Atenção",JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION){
            try {
            HashMap filtro = new HashMap();
            filtro.put("acompanhamento_idcliente", jFormattedTextNPasta.getText()); //Integer.parseInt(jTextFieldCodAcomp.getText())
            JasperPrint print = JasperFillManager.fillReport("C:\\FichaClientes\\TodosAcompanhamentos.jasper",filtro,getConnection()); //
            JasperViewer.viewReport(print, false);
            jTextAreaDescricao.setText("");
            jTextFieldCodAcomp.setText("");
            jDateChooser1.setDate(null);
            jTableRelatorio.revalidate();
            jTableRelatorio.setVisible(false);
            dispose();
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao imprimir "+ex);
            }
        }
    }//GEN-LAST:event_jButtonImprimirTodosActionPerformed
    
    //  METÓDO PARA PREENCHER A TABELA DE RELATÓRIOS
    public void preencheTabela(String sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"Cod. Acompanhamento","Nº do CPF","Data da Atualização","Narração dos Fatos"};
        conex.getConnection();
        conex.executasql(sql);
        try{
            conex.rs.first();
            do{
            dados.add(new Object[]{conex.rs.getInt("cod_acompanhamento"),conex.rs.getString("acompanhamento_idcliente"),conex.rs.getDate("acompanhamento_data"),conex.rs.getString("acompanhamento_descricao")});
            }while(conex.rs.next());
        }catch(SQLException ex){
        JOptionPane.showMessageDialog(rootPane, "Busque por outro usuário para preencher a tabela");
    }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableRelatorio.setModel(modelo);
        jTableRelatorio.getColumnModel().getColumn(0).setPreferredWidth(140);
        jTableRelatorio.getColumnModel().getColumn(0).setResizable(false);
        jTableRelatorio.getColumnModel().getColumn(1).setPreferredWidth(230);
        jTableRelatorio.getColumnModel().getColumn(1).setResizable(false);
        jTableRelatorio.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableRelatorio.getColumnModel().getColumn(2).setResizable(false);
        jTableRelatorio.getColumnModel().getColumn(3).setPreferredWidth(296); 
        jTableRelatorio.getColumnModel().getColumn(3).setResizable(false);
        jTableRelatorio.getColumnModel().getSelectionModel();
        jTableRelatorio.getColumnModel().setColumnSelectionAllowed(true);
        jTableRelatorio.getTableHeader().setReorderingAllowed(false);
        jTableRelatorio.setAutoResizeMode(jTableRelatorio.AUTO_RESIZE_OFF);
        jTableRelatorio.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        conex.desconectar();
    }
    
        // METÓDO PARA IMPRIMIR O RELATÓRIO DE ATUALIZAÇÃO
        private void imprimirFicha(){
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão do relatório? ", "Atenção",JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION){
            try {
            HashMap filtro = new HashMap();
            filtro.put("cod_acompanhamento", Integer.parseInt(jTextFieldCodAcomp.getText())); 
            JasperPrint print = JasperFillManager.fillReport("C:\\FichaClientes\\FichaAcompanhamento.jasper",filtro,getConnection());
            JasperViewer.viewReport(print, false);
            jTextAreaDescricao.setText("");
            jTextFieldCodAcomp.setText("");
            jDateChooser1.setDate(null);
            jTableRelatorio.revalidate();
            jTableRelatorio.setVisible(false);
            dispose();
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao imprimir "+ex);
            }
        }
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonImprimirTodos;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFormattedTextField jFormattedTextNPasta;
    private javax.swing.JLabel jLabelCodAcompanhamento;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelRelatorio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableRelatorio;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldCodAcomp;
    // End of variables declaration//GEN-END:variables
}
