package view;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import modeloConection.ConexaoBD;
import static modeloConection.ConexaoBD.con;

/**
 *
 * @author Nilmar
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    ConexaoBD conecta = new ConexaoBD();
    FichaCadastroUsuarios telaUser = new FichaCadastroUsuarios();
    FichaCadastroClientes telaCliente = new FichaCadastroClientes();
    Acompanhamento telaAcompanhamento = new Acompanhamento();
    Relatorio telaRelatorioAcomp = new Relatorio();
    TelaAssistidos telaAssistidos = new TelaAssistidos();

    public TelaPrincipal(String usuario) {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_justica.png")).getImage());
        jLabelUsuario.setText(usuario);
        conecta.getConnection();
    }
    
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabelFundoTelaPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuAcompanhamento = new javax.swing.JMenu();
        jMenuItemAcompanhar = new javax.swing.JMenuItem();
        jMenuItemRelatorios = new javax.swing.JMenuItem();
        jMenu_Pesquisa = new javax.swing.JMenu();
        jMenuItem_Consultar_Assistido = new javax.swing.JMenuItem();
        jMenuItem_Consultar_Aluno = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("<html><b>USUÁRIO:");

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelFundoTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/judge-hammer-law-rights-wood(1).jpg"))); // NOI18N
        jLabelFundoTelaPrincipal.setText("jLabel2");
        getContentPane().add(jLabelFundoTelaPrincipal);
        jLabelFundoTelaPrincipal.setBounds(0, 0, 890, 490);

        jMenuBar1.setForeground(new java.awt.Color(102, 102, 102));

        jMenuCadastro.setText("<html><b>CADASTRO");

        jMenuItemClientes.setText("CLIENTES");
        jMenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientesActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemClientes);

        jMenuItemUsuarios.setText("USUÁRIOS");
        jMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemUsuarios);

        jMenuBar1.add(jMenuCadastro);

        jMenuAcompanhamento.setText("<html><b>DIÁRIO DE ATENDIMENTO");

        jMenuItemAcompanhar.setText("ACOMPANHAMENTO PROCESSUAL");
        jMenuItemAcompanhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcompanharActionPerformed(evt);
            }
        });
        jMenuAcompanhamento.add(jMenuItemAcompanhar);

        jMenuItemRelatorios.setText("RELATÓRIO DE ACOMPANHAMENTO");
        jMenuItemRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatoriosActionPerformed(evt);
            }
        });
        jMenuAcompanhamento.add(jMenuItemRelatorios);

        jMenuBar1.add(jMenuAcompanhamento);

        jMenu_Pesquisa.setText("<html>\n<b>\nPESQUISA");

        jMenuItem_Consultar_Assistido.setText("CONSULTAR ASSISTIDO");
        jMenuItem_Consultar_Assistido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Consultar_AssistidoActionPerformed(evt);
            }
        });
        jMenu_Pesquisa.add(jMenuItem_Consultar_Assistido);

        jMenuItem_Consultar_Aluno.setText(" CONSULTAR ALUNO");
        jMenuItem_Consultar_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Consultar_AlunoActionPerformed(evt);
            }
        });
        jMenu_Pesquisa.add(jMenuItem_Consultar_Aluno);

        jMenuBar1.add(jMenu_Pesquisa);

        jMenuSair.setText("<html><b>SAIR");

        jMenuItemSair.setText("SAIR");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(895, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     
    //  AÇÃO AO CLICAR NO BOTÃO DE CADASTAR CLIENTES
    private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientesActionPerformed
      /*  try {
            conecta.executasql("select *from usuarios where nome_usuario='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo_usuario").equals("Atendente") || conecta.rs.getString("tipo_usuario").equals("Administrador")){
                telaCliente.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para realizar esta operação!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para realizar esta operação!");
        }*/
        telaCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItemClientesActionPerformed

    
    // AÇÃO DO BOTÃO DE CADASTRAR USUÁRIOS
    private void jMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosActionPerformed
     /*   try {
            conecta.executasql("select *from usuarios where nome_usuario='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo_usuario").equals("Administrador")){
                telaUser.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para realizar esta operação!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para realizar esta operação!");
        }*/
        telaUser.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuariosActionPerformed

    
    // AÇÃO DO BOTÃO ACOMPANHAMENTO DO CLIENTE
    private void jMenuItemAcompanharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcompanharActionPerformed
     /*   try {
            conecta.executasql("select *from usuarios where nome_usuario='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo_usuario").equals("Atendente") || conecta.rs.getString("tipo_usuario").equals("Administrador")){
                telaAcompanhamento.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para realizar esta operação!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para realizar esta operação!");
        }*/
        telaAcompanhamento.setVisible(true);
    }//GEN-LAST:event_jMenuItemAcompanharActionPerformed

    
    // AÇÃO DO BOTÃO SAIR
    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    
    private void jMenuItemRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatoriosActionPerformed
        telaRelatorioAcomp.setVisible(true);
    }//GEN-LAST:event_jMenuItemRelatoriosActionPerformed

    // BOTÃO PARA CONSULTAR ASSISTIDO
    private void jMenuItem_Consultar_AssistidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Consultar_AssistidoActionPerformed
        String cpf = JOptionPane.showInputDialog("Insira o CPF do Cliente: ");
    }//GEN-LAST:event_jMenuItem_Consultar_AssistidoActionPerformed

    // BOTÃO PARA CONSULTAR ALUNO
    private void jMenuItem_Consultar_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Consultar_AlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_Consultar_AlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFundoTelaPrincipal;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenu jMenuAcompanhamento;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAcompanhar;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemRelatorios;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenuItem jMenuItem_Consultar_Aluno;
    private javax.swing.JMenuItem jMenuItem_Consultar_Assistido;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenu_Pesquisa;
    // End of variables declaration//GEN-END:variables
}
