/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelBeans.BeansPasta;
import modelBeans.ModeloTabela;
import modeloConection.ConexaoBD;
import modeloDao.DAOPasta;

/**
 *
 * @author 44314298839
 */
public class Teste extends javax.swing.JFrame {

    BeansPasta mod = new BeansPasta();
    ConexaoBD conex = new ConexaoBD();
    DAOPasta dao = new DAOPasta();
    int flag = 0;

    /**
     * Creates new form Teste
     */
    public Teste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField_id_pasta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton_Budcar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Processos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Titulo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Status = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Alunos = new javax.swing.JTable();
        jToggleButton_Adicionar = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton_Novo = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton_Salvar = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jFormattedTextField_Cpf_Cliente = new javax.swing.JFormattedTextField();
        jButton_Buscar_aluno = new javax.swing.JButton();
        jFormattedTextField_pesquisar_aluno = new javax.swing.JFormattedTextField();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nº da Pasta");

        jTextField_id_pasta.setEnabled(false);
        jTextField_id_pasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_id_pastaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome do Assistido");

        jTextField2.setEnabled(false);

        jLabel3.setText("CPF do Assistido");

        jTextField4.setEnabled(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel4.setText("Telefone");

        jButton_Budcar.setText("Buscar");
        jButton_Budcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BudcarActionPerformed(evt);
            }
        });

        jTable_Processos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Processos.setEnabled(false);
        jTable_Processos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ProcessosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Processos);

        jLabel5.setText("Título do Pasta");

        jTextField_Titulo.setText("ex: Processo de Divorcio");
        jTextField_Titulo.setEnabled(false);
        jTextField_Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TituloActionPerformed(evt);
            }
        });

        jLabel6.setText("Data de Início");

        jDateChooser1.setEnabled(false);

        jLabel7.setText("Data de Conclusão");

        jDateChooser2.setEnabled(false);

        jLabel8.setText("Status");

        jTextField_Status.setText("ex: Cancelado, Em andamento, Vencido, Perdido");
        jTextField_Status.setEnabled(false);

        jLabel9.setText("Professor Responsável");

        jComboBox1.setEnabled(false);

        jLabel10.setText("Telefone");

        jTextField7.setEnabled(false);

        jLabel11.setText("CPF ");

        jTextField8.setEnabled(false);

        jLabel12.setText("Alunos");

        jTable_Alunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable_Alunos);

        jToggleButton_Adicionar.setText("Adicionar");
        jToggleButton_Adicionar.setEnabled(false);
        jToggleButton_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_AdicionarActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Expluir");
        jToggleButton2.setEnabled(false);

        jToggleButton_Novo.setText("Novo");
        jToggleButton_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_NovoActionPerformed(evt);
            }
        });

        jToggleButton4.setText("Editar");
        jToggleButton4.setEnabled(false);

        jToggleButton_Salvar.setText("Salvar");
        jToggleButton_Salvar.setEnabled(false);
        jToggleButton_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_SalvarActionPerformed(evt);
            }
        });

        jToggleButton6.setText("Cancelar");
        jToggleButton6.setEnabled(false);

        jToggleButton7.setText("Excluir");
        jToggleButton7.setEnabled(false);

        jLabel13.setText("Registro OAB");

        jTextField10.setEnabled(false);

        try {
            jFormattedTextField_Cpf_Cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton_Buscar_aluno.setText("Buscar Aluno");
        jButton_Buscar_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Buscar_alunoActionPerformed(evt);
            }
        });

        try {
            jFormattedTextField_pesquisar_aluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_id_pasta, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jToggleButton_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton_Adicionar)
                                .addGap(27, 27, 27)
                                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jFormattedTextField_pesquisar_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Buscar_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(12, 12, 12)
                                                    .addComponent(jLabel6)
                                                    .addGap(64, 64, 64))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addGap(0, 0, Short.MAX_VALUE))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(78, 78, 78)
                                            .addComponent(jLabel11)
                                            .addGap(187, 187, 187)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jFormattedTextField_Cpf_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jButton_Budcar)))
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_id_pasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField_Cpf_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Budcar))
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jTextField_Titulo)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel13))))
                    .addComponent(jTextField_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton_Adicionar)
                    .addComponent(jToggleButton2)
                    .addComponent(jButton_Buscar_aluno)
                    .addComponent(jFormattedTextField_pesquisar_aluno))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton_Novo)
                    .addComponent(jToggleButton4)
                    .addComponent(jToggleButton_Salvar)
                    .addComponent(jToggleButton6)
                    .addComponent(jToggleButton7))
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_id_pastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_id_pastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_id_pastaActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    // AÇÃO DO BOTÃO BUSCAR
    private void jButton_BudcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BudcarActionPerformed
        preencheTabelaClientes("select id_pasta,cpf_assistido,titulo_pasta,data_inicio from pastas where cpf_assistido like'%"+jFormattedTextField_Cpf_Cliente.getText()+"%'");
        jTable_Processos.setVisible(true);
        jTable_Processos.setEnabled(true);
    }//GEN-LAST:event_jButton_BudcarActionPerformed

    private void jTextField_TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TituloActionPerformed

    private void jToggleButton_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_AdicionarActionPerformed

        
    }//GEN-LAST:event_jToggleButton_AdicionarActionPerformed

    // AÇÃO DO BOTÃO NOVO
    private void jToggleButton_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_NovoActionPerformed

    }//GEN-LAST:event_jToggleButton_NovoActionPerformed

    // AÇÃO DO BOTÃO SALVAR
    private void jToggleButton_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_SalvarActionPerformed
        if (flag == 1) {
            mod.setCpf_assistido(jFormattedTextField_Cpf_Cliente.getText());
            mod.setTitulo_Pasta(jTextField_Titulo.getText());
            mod.setData_Inicio(jDateChooser1.getDate());
            mod.setData_Fim(jDateChooser2.getDate());
            mod.setStatus(jTextField_Status.getText());
            dao.salvar(mod);

            jFormattedTextField_Cpf_Cliente.setText("");
            jTextField_Titulo.setText("");
            jTextField_Status.setText("");
            jDateChooser1.setDate(null);
            jDateChooser2.setDate(null);

            /*
                jTextFieldNome.setEnabled(!true);
                jFormattedTextFieldCPF.setEnabled(!true);
                jFormattedTextFieldTelefone.setEnabled(!true);
                jTextFieldEndereco.setEnabled(!true);
                jTextFieldBairro.setEnabled(!true);
                jTextFieldEstado.setEnabled(!true);
                jTextFieldCidade.setEnabled(!true);
                jFormattedTextFieldNumeroCasa.setEnabled(!true);
                jComboBox_Professor.setEnabled(!false);*/
            jToggleButton_Salvar.setEnabled(!true);
        }
    }
        
    //  METÓDO PARA PREENCHER A TABELA CLIENTES
    public void preencheTabelaClientes(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Nº da Pasta", "CPF", "Titulo" ,"Data_Inicio"};
        conex.getConnection();
        conex.executasql(sql);
        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getInt("id_pasta"), conex.rs.getString("cpf_assistido"), conex.rs.getString("titulo_pasta"), conex.rs.getString("data_inicio")});
            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Busque por outro assistido para preencher a tabela");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTable_Processos.setModel(modelo);
        jTable_Processos.getColumnModel().getColumn(0).setPreferredWidth(92);
        jTable_Processos.getColumnModel().getColumn(0).setResizable(false);
        jTable_Processos.getColumnModel().getColumn(1).setPreferredWidth(440);
        jTable_Processos.getColumnModel().getColumn(1).setResizable(false);
        jTable_Processos.getColumnModel().getColumn(2).setPreferredWidth(250);
        jTable_Processos.getColumnModel().getColumn(2).setResizable(false);
        jTable_Processos.getColumnModel().getColumn(3).setPreferredWidth(122);
        jTable_Processos.getColumnModel().getColumn(3).setResizable(false);
        jTable_Processos.getTableHeader().setReorderingAllowed(false);
        jTable_Processos.setAutoResizeMode(jTable_Processos.AUTO_RESIZE_OFF);
        jTable_Processos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconectar();
    }//GEN-LAST:event_jToggleButton_SalvarActionPerformed

    //  METÓDO PARA PREENCHER A TABELA ALUNOS
    public void preencheTabelaAlunos(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Nome do Aluno", "CPF do aluno", "Telefone"};
        conex.getConnection();
        conex.executasql(sql);
        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getString("nome_aluno"), conex.rs.getString("cpf_aluno"), conex.rs.getString("telefone_aluno")});
            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Busque por outro aluno para preencher a tabela");
        }
        ModeloTabela modelo1 = new ModeloTabela(dados, colunas);
        jTable_Processos.setModel(modelo1);
        jTable_Processos.getColumnModel().getColumn(0).setPreferredWidth(92);
        jTable_Processos.getColumnModel().getColumn(0).setResizable(false);
        jTable_Processos.getColumnModel().getColumn(1).setPreferredWidth(440);
        jTable_Processos.getColumnModel().getColumn(1).setResizable(false);
        jTable_Processos.getColumnModel().getColumn(2).setPreferredWidth(250);
        jTable_Processos.getColumnModel().getColumn(2).setResizable(false);
        jTable_Processos.getTableHeader().setReorderingAllowed(false);
        jTable_Processos.setAutoResizeMode(jTable_Alunos.AUTO_RESIZE_OFF);
        jTable_Processos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconectar();
    }   
    
    // AÇÃO DO CLIQUE DO MOUSE
    private void jTable_ProcessosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ProcessosMouseClicked
        String id_pasta =""+jTable_Processos.getValueAt(jTable_Processos.getSelectedRow(), 0);
        conex.getConnection();
        conex.executasql("select *from pastas where id_pasta='"+id_pasta+"'");
        try {
            conex.rs.first();
            jFormattedTextField_Cpf_Cliente.setText(conex.rs.getString("cpf_assistido"));
            jTextField_Titulo.setText(conex.rs.getString("titulo_pasta"));
            jDateChooser1.setDate(conex.rs.getDate("data_inicio"));
            jDateChooser2.setDate(conex.rs.getDate("data_fim"));
            jTextField_id_pasta.setText(String.valueOf(conex.rs.getInt("id_pasta")));
            jTextField_Status.setText(conex.rs.getString("status"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados "+ex);
        }
        conex.desconectar();
    }//GEN-LAST:event_jTable_ProcessosMouseClicked

    
    // BUSCAR ALUNO
    private void jButton_Buscar_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Buscar_alunoActionPerformed
        preencheTabelaAlunos("select nome_aluno,cpf_aluno,telefone_aluno from alunos where cpf_aluno like'%"+jFormattedTextField_pesquisar_aluno.getText()+"%'");
        jTable_Alunos.setVisible(true);
        jTable_Alunos.setEnabled(true);
    }//GEN-LAST:event_jButton_Buscar_alunoActionPerformed

    /*
    // METÓDO PARA BUSCAR O PROFESSOR NO BANCO DE DADOS
    public void preencherProfessor(){
        conex.getConnection();
        conex.executasql("select *from professores order by nome_professor"); 
        try {
            conex.rs.first();
            jComboBox_.removeAllItems();
            do{
                jComboBox_Professor.addItem(conex.rs.getString("nome_professor"));
            }while(conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o professor "+ex);
        }
        conex.desconectar();
    }*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Budcar;
    private javax.swing.JButton jButton_Buscar_aluno;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JFormattedTextField jFormattedTextField_Cpf_Cliente;
    private javax.swing.JFormattedTextField jFormattedTextField_pesquisar_aluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable_Alunos;
    private javax.swing.JTable jTable_Processos;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField_Status;
    private javax.swing.JTextField jTextField_Titulo;
    private javax.swing.JTextField jTextField_id_pasta;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton_Adicionar;
    private javax.swing.JToggleButton jToggleButton_Novo;
    private javax.swing.JToggleButton jToggleButton_Salvar;
    // End of variables declaration//GEN-END:variables
}
